###################################################################

# Created by write_sdc on Sat Nov 23 22:14:14 2024

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_max_fanout 4 [current_design]
set_max_area 0
set_driving_cell -lib_cell INVX1TS [get_ports clk]
set_driving_cell -lib_cell INVX1TS [get_ports xload]
set_driving_cell -lib_cell INVX1TS [get_ports cload]
set_driving_cell -lib_cell INVX1TS [get_ports {caddr[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {caddr[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {caddr[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {caddr[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {caddr[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {caddr[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xaddr[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xaddr[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xaddr[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xaddr[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xaddr[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xaddr[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {cin[0]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[15]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[14]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[13]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[12]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[11]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[10]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[9]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[8]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[7]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[6]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[5]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[4]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[3]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[2]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[1]}]
set_driving_cell -lib_cell INVX1TS [get_ports {xin[0]}]
set_load -pin_load 0.005 [get_ports {xCurr[15]}]
set_load -pin_load 0.005 [get_ports {xCurr[14]}]
set_load -pin_load 0.005 [get_ports {xCurr[13]}]
set_load -pin_load 0.005 [get_ports {xCurr[12]}]
set_load -pin_load 0.005 [get_ports {xCurr[11]}]
set_load -pin_load 0.005 [get_ports {xCurr[10]}]
set_load -pin_load 0.005 [get_ports {xCurr[9]}]
set_load -pin_load 0.005 [get_ports {xCurr[8]}]
set_load -pin_load 0.005 [get_ports {xCurr[7]}]
set_load -pin_load 0.005 [get_ports {xCurr[6]}]
set_load -pin_load 0.005 [get_ports {xCurr[5]}]
set_load -pin_load 0.005 [get_ports {xCurr[4]}]
set_load -pin_load 0.005 [get_ports {xCurr[3]}]
set_load -pin_load 0.005 [get_ports {xCurr[2]}]
set_load -pin_load 0.005 [get_ports {xCurr[1]}]
set_load -pin_load 0.005 [get_ports {xCurr[0]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[15]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[14]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[13]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[12]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[11]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[10]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[9]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[8]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[7]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[6]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[5]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[4]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[3]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[2]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[1]}]
set_load -pin_load 0.005 [get_ports {coeffCurr[0]}]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports xload]
set_max_capacitance 0.005 [get_ports cload]
set_max_capacitance 0.005 [get_ports {caddr[5]}]
set_max_capacitance 0.005 [get_ports {caddr[4]}]
set_max_capacitance 0.005 [get_ports {caddr[3]}]
set_max_capacitance 0.005 [get_ports {caddr[2]}]
set_max_capacitance 0.005 [get_ports {caddr[1]}]
set_max_capacitance 0.005 [get_ports {caddr[0]}]
set_max_capacitance 0.005 [get_ports {xaddr[5]}]
set_max_capacitance 0.005 [get_ports {xaddr[4]}]
set_max_capacitance 0.005 [get_ports {xaddr[3]}]
set_max_capacitance 0.005 [get_ports {xaddr[2]}]
set_max_capacitance 0.005 [get_ports {xaddr[1]}]
set_max_capacitance 0.005 [get_ports {xaddr[0]}]
set_max_capacitance 0.005 [get_ports {cin[15]}]
set_max_capacitance 0.005 [get_ports {cin[14]}]
set_max_capacitance 0.005 [get_ports {cin[13]}]
set_max_capacitance 0.005 [get_ports {cin[12]}]
set_max_capacitance 0.005 [get_ports {cin[11]}]
set_max_capacitance 0.005 [get_ports {cin[10]}]
set_max_capacitance 0.005 [get_ports {cin[9]}]
set_max_capacitance 0.005 [get_ports {cin[8]}]
set_max_capacitance 0.005 [get_ports {cin[7]}]
set_max_capacitance 0.005 [get_ports {cin[6]}]
set_max_capacitance 0.005 [get_ports {cin[5]}]
set_max_capacitance 0.005 [get_ports {cin[4]}]
set_max_capacitance 0.005 [get_ports {cin[3]}]
set_max_capacitance 0.005 [get_ports {cin[2]}]
set_max_capacitance 0.005 [get_ports {cin[1]}]
set_max_capacitance 0.005 [get_ports {cin[0]}]
set_max_capacitance 0.005 [get_ports {xin[15]}]
set_max_capacitance 0.005 [get_ports {xin[14]}]
set_max_capacitance 0.005 [get_ports {xin[13]}]
set_max_capacitance 0.005 [get_ports {xin[12]}]
set_max_capacitance 0.005 [get_ports {xin[11]}]
set_max_capacitance 0.005 [get_ports {xin[10]}]
set_max_capacitance 0.005 [get_ports {xin[9]}]
set_max_capacitance 0.005 [get_ports {xin[8]}]
set_max_capacitance 0.005 [get_ports {xin[7]}]
set_max_capacitance 0.005 [get_ports {xin[6]}]
set_max_capacitance 0.005 [get_ports {xin[5]}]
set_max_capacitance 0.005 [get_ports {xin[4]}]
set_max_capacitance 0.005 [get_ports {xin[3]}]
set_max_capacitance 0.005 [get_ports {xin[2]}]
set_max_capacitance 0.005 [get_ports {xin[1]}]
set_max_capacitance 0.005 [get_ports {xin[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports xload]
set_max_fanout 4 [get_ports cload]
set_max_fanout 4 [get_ports {caddr[5]}]
set_max_fanout 4 [get_ports {caddr[4]}]
set_max_fanout 4 [get_ports {caddr[3]}]
set_max_fanout 4 [get_ports {caddr[2]}]
set_max_fanout 4 [get_ports {caddr[1]}]
set_max_fanout 4 [get_ports {caddr[0]}]
set_max_fanout 4 [get_ports {xaddr[5]}]
set_max_fanout 4 [get_ports {xaddr[4]}]
set_max_fanout 4 [get_ports {xaddr[3]}]
set_max_fanout 4 [get_ports {xaddr[2]}]
set_max_fanout 4 [get_ports {xaddr[1]}]
set_max_fanout 4 [get_ports {xaddr[0]}]
set_max_fanout 4 [get_ports {cin[15]}]
set_max_fanout 4 [get_ports {cin[14]}]
set_max_fanout 4 [get_ports {cin[13]}]
set_max_fanout 4 [get_ports {cin[12]}]
set_max_fanout 4 [get_ports {cin[11]}]
set_max_fanout 4 [get_ports {cin[10]}]
set_max_fanout 4 [get_ports {cin[9]}]
set_max_fanout 4 [get_ports {cin[8]}]
set_max_fanout 4 [get_ports {cin[7]}]
set_max_fanout 4 [get_ports {cin[6]}]
set_max_fanout 4 [get_ports {cin[5]}]
set_max_fanout 4 [get_ports {cin[4]}]
set_max_fanout 4 [get_ports {cin[3]}]
set_max_fanout 4 [get_ports {cin[2]}]
set_max_fanout 4 [get_ports {cin[1]}]
set_max_fanout 4 [get_ports {cin[0]}]
set_max_fanout 4 [get_ports {xin[15]}]
set_max_fanout 4 [get_ports {xin[14]}]
set_max_fanout 4 [get_ports {xin[13]}]
set_max_fanout 4 [get_ports {xin[12]}]
set_max_fanout 4 [get_ports {xin[11]}]
set_max_fanout 4 [get_ports {xin[10]}]
set_max_fanout 4 [get_ports {xin[9]}]
set_max_fanout 4 [get_ports {xin[8]}]
set_max_fanout 4 [get_ports {xin[7]}]
set_max_fanout 4 [get_ports {xin[6]}]
set_max_fanout 4 [get_ports {xin[5]}]
set_max_fanout 4 [get_ports {xin[4]}]
set_max_fanout 4 [get_ports {xin[3]}]
set_max_fanout 4 [get_ports {xin[2]}]
set_max_fanout 4 [get_ports {xin[1]}]
set_max_fanout 4 [get_ports {xin[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.01 [get_clocks clk]
set_clock_transition -max -fall 0.01 [get_clocks clk]
set_clock_transition -min -rise 0.01 [get_clocks clk]
set_clock_transition -min -fall 0.01 [get_clocks clk]
set_input_delay -clock clk  0.05  [get_ports xload]
set_input_delay -clock clk  0.05  [get_ports cload]
set_input_delay -clock clk  0.05  [get_ports {caddr[5]}]
set_input_delay -clock clk  0.05  [get_ports {caddr[4]}]
set_input_delay -clock clk  0.05  [get_ports {caddr[3]}]
set_input_delay -clock clk  0.05  [get_ports {caddr[2]}]
set_input_delay -clock clk  0.05  [get_ports {caddr[1]}]
set_input_delay -clock clk  0.05  [get_ports {caddr[0]}]
set_input_delay -clock clk  0.05  [get_ports {xaddr[5]}]
set_input_delay -clock clk  0.05  [get_ports {xaddr[4]}]
set_input_delay -clock clk  0.05  [get_ports {xaddr[3]}]
set_input_delay -clock clk  0.05  [get_ports {xaddr[2]}]
set_input_delay -clock clk  0.05  [get_ports {xaddr[1]}]
set_input_delay -clock clk  0.05  [get_ports {xaddr[0]}]
set_input_delay -clock clk  0.05  [get_ports {cin[15]}]
set_input_delay -clock clk  0.05  [get_ports {cin[14]}]
set_input_delay -clock clk  0.05  [get_ports {cin[13]}]
set_input_delay -clock clk  0.05  [get_ports {cin[12]}]
set_input_delay -clock clk  0.05  [get_ports {cin[11]}]
set_input_delay -clock clk  0.05  [get_ports {cin[10]}]
set_input_delay -clock clk  0.05  [get_ports {cin[9]}]
set_input_delay -clock clk  0.05  [get_ports {cin[8]}]
set_input_delay -clock clk  0.05  [get_ports {cin[7]}]
set_input_delay -clock clk  0.05  [get_ports {cin[6]}]
set_input_delay -clock clk  0.05  [get_ports {cin[5]}]
set_input_delay -clock clk  0.05  [get_ports {cin[4]}]
set_input_delay -clock clk  0.05  [get_ports {cin[3]}]
set_input_delay -clock clk  0.05  [get_ports {cin[2]}]
set_input_delay -clock clk  0.05  [get_ports {cin[1]}]
set_input_delay -clock clk  0.05  [get_ports {cin[0]}]
set_input_delay -clock clk  0.05  [get_ports {xin[15]}]
set_input_delay -clock clk  0.05  [get_ports {xin[14]}]
set_input_delay -clock clk  0.05  [get_ports {xin[13]}]
set_input_delay -clock clk  0.05  [get_ports {xin[12]}]
set_input_delay -clock clk  0.05  [get_ports {xin[11]}]
set_input_delay -clock clk  0.05  [get_ports {xin[10]}]
set_input_delay -clock clk  0.05  [get_ports {xin[9]}]
set_input_delay -clock clk  0.05  [get_ports {xin[8]}]
set_input_delay -clock clk  0.05  [get_ports {xin[7]}]
set_input_delay -clock clk  0.05  [get_ports {xin[6]}]
set_input_delay -clock clk  0.05  [get_ports {xin[5]}]
set_input_delay -clock clk  0.05  [get_ports {xin[4]}]
set_input_delay -clock clk  0.05  [get_ports {xin[3]}]
set_input_delay -clock clk  0.05  [get_ports {xin[2]}]
set_input_delay -clock clk  0.05  [get_ports {xin[1]}]
set_input_delay -clock clk  0.05  [get_ports {xin[0]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[15]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[14]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[13]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[12]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[11]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[10]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[9]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[8]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[7]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[6]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[5]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[4]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[3]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[2]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[1]}]
set_output_delay -clock clk  0.05  [get_ports {xCurr[0]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[15]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[14]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[13]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[12]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[11]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[10]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[9]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[8]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[7]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[6]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[5]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[4]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[3]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[2]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[1]}]
set_output_delay -clock clk  0.05  [get_ports {coeffCurr[0]}]
